export type DraftType = "CALL_SCRIPT" | "SMS_MESSAGE" | "CHART_NOTE" | "WEEKLY_SUMMARY";

export interface AiDraftInput {
  draftType: DraftType;
  patientDisplayName: string;
  patientInternalId: string;
  protocolName: string;
  lastTreatmentDate?: string | null;
  nextDueDate?: string | null;
  status: string;
  outreachHistory?: string;
  additionalContext?: string;
}

function generateMockDraft(input: AiDraftInput): string {
  const {
    draftType,
    patientDisplayName,
    patientInternalId,
    protocolName,
    lastTreatmentDate,
    nextDueDate,
    status,
    outreachHistory,
  } = input;

  const lastDate = lastTreatmentDate
    ? new Date(lastTreatmentDate).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })
    : "unknown date";
  const nextDate = nextDueDate
    ? new Date(nextDueDate).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })
    : "not yet scheduled";

  switch (draftType) {
    case "CALL_SCRIPT":
      return `CALL SCRIPT — ${patientDisplayName} (${patientInternalId})
Treatment: ${protocolName} | Status: ${status}

Hello, may I speak with ${patientDisplayName}?

[If patient answers:]
Hi, this is [Your Name] calling from [Practice Name]. I'm reaching out because we have you scheduled for your ${protocolName} treatment, which was due on ${nextDate}.

We want to make sure you're staying on track with your treatment plan. Missing doses can affect your treatment outcomes.

Are you available to come in this week to complete your treatment? [Pause for response]

[If yes:] Wonderful! Let me get that scheduled for you right now. What day works best?
[If no:] I understand. Is there a specific reason or concern preventing you from coming in? [Address concern]

We can also connect you with your provider if you have any questions about your treatment.

[End of call:]
Great, I'll note this in your chart. Is there anything else I can help you with? Thank you, have a great day.

[If voicemail:]
Hello, this is a message for ${patientDisplayName}. This is [Your Name] from [Practice Name], calling regarding your ${protocolName} treatment appointment. Your treatment was scheduled for ${nextDate}. Please call us back at [Phone Number] at your earliest convenience so we can reschedule. Thank you.`;

    case "SMS_MESSAGE":
      return `Hi ${patientDisplayName}, this is [Practice Name] reaching out about your ${protocolName} treatment due ${nextDate}. Please call us at [Phone Number] to schedule your appointment. Reply STOP to opt out.`;

    case "CHART_NOTE":
      return `CHART NOTE — ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
Patient: ${patientDisplayName} (${patientInternalId})

Patient was contacted regarding ${
        status === "OVERDUE" || status === "HIGH_PRIORITY"
          ? "missed"
          : "upcoming"
      } ${protocolName} appointment originally due on ${nextDate}.

${outreachHistory ? `Outreach history: ${outreachHistory}` : "Staff reached out via phone."}

Last treatment administered: ${lastDate}.
Current treatment status: ${status}.

Follow-up plan: Patient to be rescheduled for ${protocolName} as soon as possible. Provider notified of treatment gap. Will continue outreach attempts if no response within 48 hours.

Documentation entered by: [Staff Name]
Date: ${new Date().toLocaleDateString()}`;

    case "WEEKLY_SUMMARY":
      return `WEEKLY TREATMENT CONTINUITY SUMMARY
Week of ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
Generated by: Adherix

This summary covers active treatment enrollments and outreach activity for the current week.

OVERDUE / HIGH PRIORITY:
- ${patientDisplayName} (${patientInternalId}) — ${protocolName} — Last treated: ${lastDate} — Status: ${status}

ACTION ITEMS:
- Review all HIGH_PRIORITY patients with provider
- Schedule overdue appointments before end of week
- Document all outreach attempts in chart notes
- Follow up on pending reschedules

Please review and take appropriate action. Contact the office manager with questions.`;

    default:
      return "Draft type not supported.";
  }
}

export async function generateAiDraft(input: AiDraftInput): Promise<string> {
  const provider = process.env.AI_PROVIDER ?? "mock";

  if (provider === "mock") {
    return generateMockDraft(input);
  }

  if (provider === "openai") {
    const allowPhi = process.env.ALLOW_PHI_TO_AI === "true";
    const patientRef = allowPhi
      ? `${input.patientDisplayName} (ID: ${input.patientInternalId})`
      : `Patient ID: ${input.patientInternalId}`;

    const prompt = buildPrompt({ ...input, patientRef });

    try {
      const res = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${process.env.AI_API_KEY}`,
        },
        body: JSON.stringify({
          model: process.env.AI_MODEL ?? "gpt-4o",
          messages: [{ role: "user", content: prompt }],
          max_tokens: 800,
          temperature: 0.3,
        }),
      });

      if (!res.ok) throw new Error(`OpenAI API error: ${res.status}`);
      const data = await res.json();
      return data.choices?.[0]?.message?.content ?? "Failed to generate content.";
    } catch (err) {
      console.error("AI generation failed, using mock:", err);
      return generateMockDraft(input);
    }
  }

  return generateMockDraft(input);
}

function buildPrompt(input: AiDraftInput & { patientRef: string }): string {
  const { draftType, patientRef, protocolName, lastTreatmentDate, nextDueDate, status } = input;

  const context = `Patient: ${patientRef}. Treatment: ${protocolName}. Last treated: ${lastTreatmentDate ?? "unknown"}. Next due: ${nextDueDate ?? "not scheduled"}. Status: ${status}.`;

  switch (draftType) {
    case "CALL_SCRIPT":
      return `You are a healthcare staff assistant. Generate a professional, empathetic phone call script for a psychiatric practice staff member to use when calling a patient about a missed or upcoming treatment. ${context} Keep it concise and professional. Do not use placeholders for the patient's name.`;
    case "SMS_MESSAGE":
      return `Generate a brief, HIPAA-conscious SMS reminder for a patient about a psychiatric treatment appointment. ${context} Keep under 160 characters if possible. Include a callback number placeholder.`;
    case "CHART_NOTE":
      return `Generate a Practice Fusion-style clinical chart note documenting outreach for a missed psychiatric treatment. ${context} Use professional clinical language. Include date, patient reference, treatment status, outreach action taken, and follow-up plan.`;
    case "WEEKLY_SUMMARY":
      return `Generate a weekly treatment continuity summary for a psychiatric practice. ${context} Include action items and provider notifications needed.`;
    default:
      return `Generate clinical content for ${draftType}. ${context}`;
  }
}
